dna/urls.py
from django.urls import path
from .views import index, get_dnas, create_dna, dna_detail, statistic, stats

urlpatterns = [
    path('dna/', index, name='dna'),
    path('get_dnas/', get_dnas, name='get_dnas'),
    path('simian/', create_dna, name='simian'),
    path('dna_detail/<int:pk>/', dna_detail, name='dna_detail'),
    path('statistic/', statistic, name='statistic'),
    path('stats/', stats, name='stats'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from .routers import router
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api/', include('dna.urls')),
    path('', include(('dna.urls', 'dna'), namespace='dna')),
    path('', include(('users.urls', 'users'), namespace='users')),
]

users/urls.py
from django.urls import path
from .views import do_login, do_logout, create_user, update_user

urlpatterns = [
    path('', do_login, name='login'),
    path('logout/', do_logout, name='logout'),
    path('register/', create_user, name='register'),
    path('update/<int:id>/', update_user, name='update_user'),
]

dna/models.py
from django.db import models

class Dna(models.Model):
    id = models.AutoField(primary_key=True)
    dna = models.CharField(max_length=250)
    categoria = models.CharField(max_length=250)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User

class UserModelForm(forms.ModelForm):
    User._meta.get_field('first_name').blank = False
    User._meta.get_field('email').blank = False
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'maxlength':60}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'maxlength':100}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'maxlength':60}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'maxlength':60}),
        }
        labels = {
            'first_name': 'Nome',
            'email': 'Email',
			'username': 'Usuário',
			'password': 'Senha',
        }

    def save(self, commit=True):
        user = super(UserModelForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

dna/views.py
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.http import JsonResponse
from django.shortcuts import render
from .models import Dna
from .serializers import DnaSerializer
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    return render(request, 'index.html')

@api_view(['GET'])
def get_dnas(request):
    dnas = Dna.objects.all()
    serializer = DnaSerializer(dnas, many=True, context={'request': request})
    return Response(serializer.data)

@api_view(['POST'])
def create_dna(request):
	serializer = DnaSerializer(data=request.data)
	if serializer.is_valid():
		serializer.save()
		if request.data['categoria'] == 'Símio':
			return Response(serializer.data, status=status.HTTP_200_OK)
		else:
			return Response(serializer.data, status=status.HTTP_403_FORBIDDEN)
	return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

@api_view(['GET', 'PUT', 'DELETE'])
def dna_detail(request, pk):
	try:
		dna = Dna.objects.get(pk=pk)
	except Dna.DoesNotExist:
		return Response(status=status.HTTP_404_NOT_FOUND)

	if request.method == 'GET':
		serializer = DnaSerializer(dna)
		return Response(serializer.data)

	elif request.method == 'PUT':
		serializer = DnaSerializer(dna, data=request.data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_200_OK)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

	elif request.method == 'DELETE':
		dna.delete()
		return Response(status=status.HTTP_204_NO_CONTENT)

@api_view(['GET'])
def stats(request):
    count_mutant_dna = 0;
    count_human_dna = 0;

    dnas = Dna.objects.all()
    for dna in dnas:
        if dna.categoria == 'Símio':
            count_mutant_dna = count_mutant_dna + 1;
        else:
            count_human_dna = count_human_dna + 1;
    ratio = count_mutant_dna / count_human_dna;

    return Response({'count_mutant_dna': count_mutant_dna, 'count_human_dna': count_human_dna, 'ratio': ratio})

@login_required
def statistic(request):
    return render(request, 'statistic.html')

users/views.py
from django.shortcuts import render, redirect
from users.forms import UserModelForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def create_user(request):
    form = UserModelForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request, 'register.html', {'form': form})

@login_required
def update_user(request, id=1):
    id = request.user.id
    user = User.objects.get(id=id)
    form = UserModelForm(request.POST or None, instance=user)

    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request, 'users-form.html', {'form': form, 'user': user})

def do_login(request):
    form = UserModelForm(request.POST or None)
    error = ''

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            if user.is_active:
                try:
                    login(request, user)
                    return redirect('/dna')
                except:
                    error = 'Internal error'
            else:
                error = 'Inactive user'
        else:
            error = 'Invalid username or password!'

    return render(request, 'login.html', {'form': form, 'error': error})

def do_logout(request):
    logout(request)
    return redirect('/')

dna/templates/index.html
{% extends 'layouts/base.html' %}
{% block content %}
  <div id="starting">
      <h2>DNA</h2>
      <button  type="button" class="btn btn-success" @click="getDna()" data-toggle="modal" data-target="#addDnaModal">Adicionar</button>
      <div class="search-right">
        <form method="GET" action="">
          <input class="form-control mr-sm-2" type="text" placeholder="Pesquisar" v-model="search_term" aria-label="Search">
          <button type="submit" class="btn btn-primary" v-on:click.prevent="getDnas()"><i class="fa fa-search"></i></button>
        </form>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Dna</th>
            <th scope="col">Categoria</th>
            <th scope="col" class="text-center">Ação</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="value in dnas">
            <th scope="row">${value.id}</th>
            <td>${value.dna}</td>
            <td>${value.categoria}</td>
            <td class="col-actions">
              <button class="btn btn-primary" v-on:click="getDna(value.id)" data-toggle="modal" data-target="#editDnaModal"><i class="fa fa-edit"></i> Editar</button>
              <button class="btn btn-danger" v-on:click="deleteDna(value.id)"><i class="fa fa-trash"></i> Excluir</button>
            </td>
          </tr>
        </tbody>
      </table>

      <!-- Adicionar DNA Modal -->
      <div class="modal fade" id="addDnaModal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h3 class="modal-title" id="modalTitle">Adicionar DNA</h3>
              <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
			  <div class="alert alert-success" v-if="successMessage">${ successMessage }</div>
			  <div class="alert alert-danger" v-if="errorMessage">${ errorMessage }</div>
              <div class="form-group">
                <label for="dna">Dna</label><br>
				<div v-for="(value, index) of currentDna.dna">
					<input type="text" class="form-control" placeholder="Código" v-model="currentDna.dna[index]" required="required">
				</div>
				<button type="button" class="btn btn-success" @click="addCodigo"><i class="fa fa-plus"></i> Código</button>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-close"></i> Fechar</button>
              <button type="button" class="btn btn-success" @click="addDna"><i class="fa fa-hdd-o"></i> Salvar</button>
            </div>
            
          </div>
        </div>
        <div class="loading" v-if="loading===true">Loading&#8230;</div>
      </div>
      <!-- End of add article modal -->

      <!-- Editar DNA Modal -->
      <div class="modal fade" id="editDnaModal" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h3 class="modal-title" id="modalTitle">Editar DNA</h3>
              <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
			  <div class="alert alert-success" v-if="successMessage">${ successMessage }</div>
              <div class="alert alert-danger" v-if="errorMessage">${ errorMessage }</div>
              <div class="form-group">
                <label for="dna">Dna</label>
				<div v-for="(value, index) of currentDna.dna">
					<input type="text" class="form-control" placeholder="Código" v-model="currentDna.dna[index]" required="required">
				</div>
				<button type="button" class="btn btn-success" @click="addCodigo"><i class="fa fa-plus"></i> Código</button>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal"><i class="fa fa-close"></i> Fechar</button>
			  <button type="button" class="btn btn-success" @click="updateDna"><i class="fa fa-hdd-o"></i> Salvar</button>
            </div>
            
          </div>
        </div>
        <div class="loading" v-if="loading===true">Loading&#8230;</div>
      </div>
      <!-- End of edit article modal -->
    <div class="loading" v-if="loading===true">Loading&#8230;</div>
  </div>
{% endblock %}

dna/templates/statistic.html
{% extends 'layouts/base.html' %}
{% block content %}
  <div id="starting">
      <h2>Estatística</h2>
	  <div class="panel panel-default">
		<div class="panel-body">
			Quantidade de Simian: ${stats.count_mutant_dna} <br><br>
			Quantidade de Humanos: ${stats.count_human_dna} <br><br>
			Ratio: ${stats.ratio} <br>
		</div>
	  </div>
      
      <!-- End of edit article modal -->
    <div class="loading" v-if="loading===true">Loading&#8230;</div>
  </div>
{% endblock %}

templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Mercado Livre</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container-header">
        <div class="navbar-header">
          <!-- Collapsed Hamburger -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Branding Image -->
          <a class="navbar-brand" href="/dna">
            <strong>Mercado Livre</strong>
          </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
          <!-- Left Side Of Navbar -->
          <ul class="nav nav-navbar navbar-left">
            <li class="menu-item"><a href="/dna">DNA</a></li>
            <li class="menu-item"><a href="/statistic">Estatística</a></li>
          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="nav navbar-nav navbar-right">
            <!-- Authentication Links -->
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <img src="{% static 'img/avatar-placeholder.svg' %}" alt="" width="30" class="img-circle">
                    {{ user.get_username }} <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'users:update_user' 1 %}">Perfil</a></li>
                    <li><a href="{% url 'users:logout' %}">Sair</a></li>
                </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vue.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vue-resource.js' %}"></script>

    <script type="text/javascript">
        Vue.http.headers.common['X-CSRFToken'] = "{{ csrf_token }}";
    </script>
    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>

</body>
</html>

templates/layouts/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Mercado Livre</title>
</head>
<body class="page-login">
    <div class="container-login">
        {% block content %}
        {% endblock %}
    </div>

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

users/templates/login.html
{% extends 'layouts/login.html' %}
{% load static %}
{% load bootstrap %}
{% block content %}
  <form action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}
	<div class="logo"><img src="{% static 'img/logo.png' %}" width="150"></div>
    <div class="panel panel-default">
    	<div class="panel-body box-login">
        <h3 class="title-login">Login</h3>
        <div class="form-group">
          <label for="username" class="sr-only">Usuário</label>
          <span class="fa fa-user"></span>
          <input type="text" name="username" class="form-control input-login" placeholder="Usuário" required autofocus>
        </div>
        <div class="form-group">
          <label for="password" class="sr-only">Senha</label>
          <span class="fa fa-lock"></span>
          <input type="password" name="password" class="form-control input-login" placeholder="Senha" required>
        </div>
        <div class="form-group">
          <button class="btn btn-lg btn-success btn-block" type="submit">Login</button>
        </div>
        <a href="{% url 'users:register' %}" class="link-register">Criar uma conta</a>
    		{% if error %}
    			<div class="alert alert-danger">{{error}}</div>
    		{% endif %}
      </div>
    </div>
    <div class="text-center">
      <strong>Login de Teste:</strong><br><br>
      Usuário: admin<br>
      Senha: admin<br>
    </div>
  </form>
{% endblock %}

users/templates/register.html
{% extends 'layouts/login.html' %}
{% load bootstrap %}
{% block content %}
  <div class="panel panel-default">
  	<div class="panel-body box-login">
			<h3 class="title-login">Cadastro</h3>
      <form method="POST">
          {% csrf_token %}
          {{ form|bootstrap }}
          <a href="/" class="btn btn-outline-secondary"><i class="fa fa-arrow-left"></i> Voltar</a>
  				<button type="submit" class="btn btn-success"><i class="fa fa-hdd-o"></i> Salvar</button>
      </form>
    </div>
  </div>
{% endblock %}

users/templates/users-form.html
{% extends 'layouts/base.html' %}
{% load bootstrap %}
{% block content %}
	<h2>Perfil</h2>

  <div class="panel panel-default">
  	<div class="panel-body">
  		<div class="container-form col-sm-5">
        <form method="POST" novalidate>
            {% csrf_token %}
            {{ form|bootstrap }}
            <a href="/dna" class="btn btn-outline-secondary"><i class="fa fa-arrow-left"></i> Voltar</a>
			<button type="submit" class="btn btn-success"><i class="fa fa-hdd-o"></i> Salvar</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}